package com.example.HR.enums;

public enum Major {
    COMPUTER_SCIENCE,
    INFORMATION_TECHNOLOGY,
    SOFTWARE_ENGINEERING,
    DATA_SCIENCE,
    ELECTRICAL_ENGINEERING,
    MECHANICAL_ENGINEERING,
    BUSINESS_ADMINISTRATION,
    ECONOMICS,
    LAW,
    MEDICINE
}
